# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\\design\\ui\\admin_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminPanel(object):
    def setupUi(self, AdminPanel):
        AdminPanel.setObjectName("AdminPanel")
        AdminPanel.resize(958, 708)
        self.centralwidget = QtWidgets.QWidget(AdminPanel)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setStyleSheet("font: 36pt \"MS Shell Dlg 2\";")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.mainLayout.addWidget(self.titleLabel)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.booksTab = QtWidgets.QWidget()
        self.booksTab.setObjectName("booksTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.booksTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.searchBar = QtWidgets.QLineEdit(self.booksTab)
        self.searchBar.setStyleSheet("font: 14pt \"MS Shell Dlg 2\"; padding: 10px; border: 2px solid #aaa; border-radius: 5px;")
        self.searchBar.setObjectName("searchBar")
        self.verticalLayout_2.addWidget(self.searchBar)
        self.booksScrollArea = QtWidgets.QScrollArea(self.booksTab)
        self.booksScrollArea.setWidgetResizable(True)
        self.booksScrollArea.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.booksScrollArea.setObjectName("booksScrollArea")
        self.booksContainer = QtWidgets.QWidget()
        self.booksContainer.setGeometry(QtCore.QRect(0, 0, 914, 489))
        self.booksContainer.setObjectName("booksContainer")
        self.productsVerticalLayout = QtWidgets.QVBoxLayout(self.booksContainer)
        self.productsVerticalLayout.setSpacing(10)
        self.productsVerticalLayout.setObjectName("productsVerticalLayout")
        self.booksLayout = QtWidgets.QVBoxLayout()
        self.booksLayout.setObjectName("booksLayout")
        self.productsVerticalLayout.addLayout(self.booksLayout)
        self.booksScrollArea.setWidget(self.booksContainer)
        self.verticalLayout_2.addWidget(self.booksScrollArea)
        self.pushButton = QtWidgets.QPushButton(self.booksTab)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.tabWidget.addTab(self.booksTab, "")
        self.orderTab = QtWidgets.QWidget()
        self.orderTab.setObjectName("orderTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.orderTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.orderSearchBar = QtWidgets.QLineEdit(self.orderTab)
        self.orderSearchBar.setStyleSheet("font: 14pt \"MS Shell Dlg 2\"; padding: 10px; border: 2px solid #aaa; border-radius: 5px;")
        self.orderSearchBar.setObjectName("orderSearchBar")
        self.verticalLayout_3.addWidget(self.orderSearchBar, 0, QtCore.Qt.AlignTop)
        self.ordersScrollArea = QtWidgets.QScrollArea(self.orderTab)
        self.ordersScrollArea.setWidgetResizable(True)
        self.ordersScrollArea.setObjectName("ordersScrollArea")
        self.ordersContainer = QtWidgets.QWidget()
        self.ordersContainer.setGeometry(QtCore.QRect(0, 0, 914, 525))
        self.ordersContainer.setObjectName("ordersContainer")
        self.ordersContainerLayout = QtWidgets.QVBoxLayout(self.ordersContainer)
        self.ordersContainerLayout.setSpacing(10)
        self.ordersContainerLayout.setObjectName("ordersContainerLayout")
        self.ordersLayout = QtWidgets.QVBoxLayout()
        self.ordersLayout.setObjectName("ordersLayout")
        self.ordersContainerLayout.addLayout(self.ordersLayout)
        self.ordersScrollArea.setWidget(self.ordersContainer)
        self.verticalLayout_3.addWidget(self.ordersScrollArea)
        self.tabWidget.addTab(self.orderTab, "")
        self.mainLayout.addWidget(self.tabWidget)
        AdminPanel.setCentralWidget(self.centralwidget)

        self.retranslateUi(AdminPanel)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AdminPanel)

    def retranslateUi(self, AdminPanel):
        _translate = QtCore.QCoreApplication.translate
        AdminPanel.setWindowTitle(_translate("AdminPanel", "Admin Panel - Bookstore"))
        self.titleLabel.setText(_translate("AdminPanel", "Admin Panel"))
        self.searchBar.setPlaceholderText(_translate("AdminPanel", "Поиск книг..."))
        self.pushButton.setText(_translate("AdminPanel", "Добавить книгу"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.booksTab), _translate("AdminPanel", "Книги"))
        self.orderSearchBar.setPlaceholderText(_translate("AdminPanel", "Имя пользователя..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.orderTab), _translate("AdminPanel", "Заказы"))
