# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\\layouts\\main_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(906, 724)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setStyleSheet("font: 36pt \"MS Shell Dlg 2\";")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.mainLayout.addWidget(self.titleLabel)
        self.containerLayout = QtWidgets.QHBoxLayout()
        self.containerLayout.setObjectName("containerLayout")
        self.leftMenuLayout = QtWidgets.QVBoxLayout()
        self.leftMenuLayout.setObjectName("leftMenuLayout")
        self.searchBar = QtWidgets.QLineEdit(self.centralwidget)
        self.searchBar.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.searchBar.setObjectName("searchBar")
        self.leftMenuLayout.addWidget(self.searchBar)
        self.categoriesList = QtWidgets.QListWidget(self.centralwidget)
        self.categoriesList.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.categoriesList.setObjectName("categoriesList")
        item = QtWidgets.QListWidgetItem()
        self.categoriesList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.categoriesList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.categoriesList.addItem(item)
        self.leftMenuLayout.addWidget(self.categoriesList)
        self.containerLayout.addLayout(self.leftMenuLayout)
        self.productsScrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.productsScrollArea.setWidgetResizable(True)
        self.productsScrollArea.setObjectName("productsScrollArea")
        self.productsContainer = QtWidgets.QWidget()
        self.productsContainer.setGeometry(QtCore.QRect(0, 0, 438, 638))
        self.productsContainer.setObjectName("productsContainer")
        self.productsVerticalLayout = QtWidgets.QVBoxLayout(self.productsContainer)
        self.productsVerticalLayout.setObjectName("productsVerticalLayout")
        self.productsScrollArea.setWidget(self.productsContainer)
        self.containerLayout.addWidget(self.productsScrollArea)
        self.mainLayout.addLayout(self.containerLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bookstore"))
        self.titleLabel.setText(_translate("MainWindow", "Bookstore"))
        self.searchBar.setPlaceholderText(_translate("MainWindow", "Search books..."))
        __sortingEnabled = self.categoriesList.isSortingEnabled()
        self.categoriesList.setSortingEnabled(False)
        item = self.categoriesList.item(0)
        item.setText(_translate("MainWindow", "Drama"))
        item = self.categoriesList.item(1)
        item.setText(_translate("MainWindow", "Fantasy"))
        item = self.categoriesList.item(2)
        item.setText(_translate("MainWindow", "Fary-tail"))
        self.categoriesList.setSortingEnabled(__sortingEnabled)
