# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\\design\\ui\\order_card.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OrderCard(object):
    def setupUi(self, OrderCard):
        OrderCard.setObjectName("OrderCard")
        OrderCard.resize(562, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(OrderCard.sizePolicy().hasHeightForWidth())
        OrderCard.setSizePolicy(sizePolicy)
        OrderCard.setMinimumSize(QtCore.QSize(0, 0))
        OrderCard.setMaximumSize(QtCore.QSize(16777215, 300))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(OrderCard)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.orderIdLabel = QtWidgets.QLabel(OrderCard)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.orderIdLabel.setFont(font)
        self.orderIdLabel.setObjectName("orderIdLabel")
        self.verticalLayout_2.addWidget(self.orderIdLabel)
        self.userIdLabel = QtWidgets.QLabel(OrderCard)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.userIdLabel.setFont(font)
        self.userIdLabel.setObjectName("userIdLabel")
        self.verticalLayout_2.addWidget(self.userIdLabel)
        self.paymentTypeLabel = QtWidgets.QLabel(OrderCard)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.paymentTypeLabel.setFont(font)
        self.paymentTypeLabel.setObjectName("paymentTypeLabel")
        self.verticalLayout_2.addWidget(self.paymentTypeLabel)
        self.priceLabel = QtWidgets.QLabel(OrderCard)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.priceLabel.setFont(font)
        self.priceLabel.setObjectName("priceLabel")
        self.verticalLayout_2.addWidget(self.priceLabel)
        self.addressLabel = QtWidgets.QLabel(OrderCard)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.addressLabel.setFont(font)
        self.addressLabel.setObjectName("addressLabel")
        self.verticalLayout_2.addWidget(self.addressLabel)
        self.phoneLabel = QtWidgets.QLabel(OrderCard)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.phoneLabel.setFont(font)
        self.phoneLabel.setObjectName("phoneLabel")
        self.verticalLayout_2.addWidget(self.phoneLabel)
        self.emailLabel = QtWidgets.QLabel(OrderCard)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.emailLabel.setFont(font)
        self.emailLabel.setObjectName("emailLabel")
        self.verticalLayout_2.addWidget(self.emailLabel)
        self.detailsBtn = QtWidgets.QPushButton(OrderCard)
        self.detailsBtn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.detailsBtn.setFont(font)
        self.detailsBtn.setObjectName("detailsBtn")
        self.verticalLayout_2.addWidget(self.detailsBtn)

        self.retranslateUi(OrderCard)
        QtCore.QMetaObject.connectSlotsByName(OrderCard)

    def retranslateUi(self, OrderCard):
        _translate = QtCore.QCoreApplication.translate
        self.orderIdLabel.setText(_translate("OrderCard", "Order ID: 12345"))
        self.userIdLabel.setText(_translate("OrderCard", "User ID: 6789"))
        self.paymentTypeLabel.setText(_translate("OrderCard", "Payment Type: Credit Card"))
        self.priceLabel.setText(_translate("OrderCard", "Price: $100"))
        self.addressLabel.setText(_translate("OrderCard", "Address: 123 Main St"))
        self.phoneLabel.setText(_translate("OrderCard", "Phone: (123) 456-7890"))
        self.emailLabel.setText(_translate("OrderCard", "Email: example@example.com"))
        self.detailsBtn.setText(_translate("OrderCard", "Детали заказа"))
